trigger:
- manual

stages:
- stage: 'Buildstage'
  displayName: 'BuildStage'

  jobs:
  - job: 'Buildjob'
    displayName: 'Buildjob'

    pool:
      vmImage: windows-2019
    variables:
    - name: BuildConfiguration
      value: 'Release'
    - name: BuildParameters.solution
      value: '**\*.sln'

    steps:
    - task: NuGetCommand@2
      displayName: NuGet restore
      inputs:
        solution: $(BuildParameters.solution)
    - task: VSBuild@1
      displayName: Build solution
      inputs:
        solution: '$(BuildParameters.solution)'
        msbuildArgs: '/p:DeployOnBuild=true  /p:PackageAsSingleFile=true  /p:SkipInvalidConfigurations=true  /p:PackageLocation="$(build.artifactstagingdirectory)"'
        configuration: '$(BuildConfiguration)'


    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
